### ISSUE TITLE
Swagger UI is missing id param in UI

### ISSUE THREAD

**Issue by wirthual** [jens-ox/bundesdatenkrake#14]
Hi Jens,

I just stumbled over a problem in the swagger UI and thought I let you know.

Somehow the id can not be set, only the file. 

Not sure if I am missing something.

![image](https://user-images.githubusercontent.com/2640499/222766944-4581d8c3-e7ec-4b92-ad78-f0f0789b7313.png)

Keep up the good work.

Best,
wirthual

**Comment by jens-ox** [comment]
Hi @wirthual! I just published a fix, this should now work properly ☺️
