### ISSUE TITLE
Lieferengpass-Meldungen out of date

### ISSUE THREAD

**Issue by mmnewmedia** [jens-ox/bundesdatenkrake#47]
Are there any problems due to updating the JSON of Lieferengpass: https://www.krake.dev/api/file?id=bfg-lieferengpass&file=main.json ?

There were no updates since 25.04.2023, although there are new reportings at the list of Bundesministerium für Gesundheit / pharmanet.bund.

**Comment by jens-ox** [comment]
Thanks for raising this! There was a stale automated PR open, which caused the nightly run to not raise a new one. Just triggered the workflow, should be updated in a couple of minutes.

**Comment by jens-ox** [comment]
Closing through #48
